##### 6 different envs
env_embedds :
  "item_embeddings_focused.pt":
    click_model :
      "tdPBM":
        diversity_penalty : 1.0
        MF_checkpoint : "focused_topdown"
      "mixPBM":
        diversity_penalty :
          1.0:
            MF_checkpoint : "focused_mix"
          3.0:
            MF_checkpoint : "focused_divpen"
  "item_embeddings_diffuse.pt":
    click_model :
      "tdPBM":
        diversity_penalty : 1.0
        MF_checkpoint : "diffuse_topdown"
      "mixPBM":
        diversity_penalty :
          1.0:
            MF_checkpoint : "diffuse_mix"
          3.0:
            MF_checkpoint : "diffuse_divpen"


#### Common to all envs
agent :
  "REINFORCESlate":
    beliefs : ["actor"]
    ranker : "none"
    capacity : 1
    batch_size : 1
    pi_lr: 0.003
    hidden_layers_pinet: [["256"]]
    gamma : 0.8
    item_embedds : "scratch"
    name : "REINFORCE+SoftMax"

  "SAC":
    beliefs : [["actor", "critic"]]
    ranker : "topk"
    capacity : 10000
    batch_size : 20
    q_lr: 0.001
    hidden_layers_qnet: [["256"]]
    target_update_frequency: 1
    tau : 0.002
    pi_lr: 0.003
    hidden_layers_pinet: [["256"]]
    gamma : 0.8
    auto_entropy : "True"
    alpha : 0.2
    item_embedds :
      "ideal":
        name : "SAC+topK-ideal"
      "mf":
        name : "SAC+topK-mf"

  "WolpertingerSAC":
    beliefs : [["actor", "critic"]]
    ranker : "none"
    name : "SAC+WkNN"
    capacity : 10000
    batch_size : 20
    q_lr: 0.001
    hidden_layers_qnet: [["256"]]
    target_update_frequency: 1
    tau : 0.002
    pi_lr: 0.003
    hidden_layers_pinet: [["256"]]
    gamma : 0.8
    auto_entropy : "True"
    alpha : 0.2
    item_embedds : "ideal"

  "SlateQ" :
    beliefs : "critic"
    item_embedds : "scratch"
    ranker : "none"
    name : "SlateQ"
    capacity : 10000
    batch_size : 20
    q_lr: 0.001
    hidden_layers_qnet: [["256"]]
    target_update_frequency: 1
    tau : 0.002
    gamma : 0.8

belief : "GRU"
env_name: "topics"
device: "cuda"
seed : [58407201, 496912423, 2465781, 300029, 215567, 23437561, 309081907, 548260111, 51941177, 212407167]
max_steps: 100000
check_val_every_n_epoch : 1000
val_step_length : 200
test_size : 500
random_steps : 2000

### Belief Encoder
belief_state_dim : 20
item_embedd_dim : 20

### Env
num_items : 1000
boredom_threshold : 5
recent_items_maxlen : 10
boredom_moving_window : 5
env_omega : 0.9
short_term_boost : 1.0
episode_length : 100
env_offset : 0.28
env_slope : 100
diversity_threshold : 4
topic_size : 2
num_topics : 10
